plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
}

base { archivesName = project.archives_base_name }
version = project.mod_version
group = project.maven_group

repositories {
    maven { url = "https://maven.meteordev.org/releases" }
    maven { url = "https://maven.meteordev.org/snapshots" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation files("libs/meteor-client.jar")
    implementation "meteordevelopment:orbit:0.2.4"
    modCompileOnly "meteordevelopment:baritone:1.21.10-SNAPSHOT"
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

processResources {
    filesMatching("fabric.mod.json") { expand "version": project.version }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}
